import { CharsToGroups, GroupsToChars } from "@/types";

export const groupsToChars: GroupsToChars = {
    "base": [ ["ア", "a", "k_a"], ["イ", "i", "k_i"], ["ウ", "u", "k_u"], ["エ", "e", "k_e"], ["オ", "o", "k_o"] ],
    "k": [ ["カ", "ka", "k_ka"], ["キ", "ki", "k_ki"], ["ク", "ku", "k_ku"], ["ケ", "ke", "k_ke"], ["コ", "ko", "k_ko"] ],
    "s": [ ["サ", "sa", "k_sa"], ["シ", "shi", "k_shi"], ["ス", "su", "k_su"], ["セ", "se", "k_se"], ["ソ", "so", "k_so"] ],
    "t": [ ["タ", "ta", "k_ta"], ["チ", "chi", "k_chi"], ["ツ", "tsu", "k_tsu"], ["テ", "te", "k_te"], ["ト", "to", "k_to"] ],
    "n": [ ["ナ", "na", "k_na"], ["ニ", "ni", "k_ni"], ["ヌ", "nu", "k_nu"], ["ネ", "ne", "k_ne"], ["ノ", "no", "k_no"] ],
    "h": [ ["ハ", "ha", "k_ha"], ["ヒ", "hi", "k_hi"], ["フ", "fu", "k_fu"], ["ヘ", "he", "k_he"], ["ホ", "ho", "k_ho"] ],
    "m": [ ["マ", "ma", "k_ma"], ["ミ", "mi", "k_mi"], ["ム", "mu", "k_mu"], ["メ", "me", "k_me"], ["モ", "mo", "k_mo"] ],
    "y": [ ["ヤ", "ya", "k_ya"], ["ユ", "yu", "k_yu"], ["ヨ", "yo", "k_yo"] ],
    "r": [ ["ラ", "ra", "k_ra"], ["リ", "ri", "k_ri"], ["ル", "ru", "k_ru"], ["レ", "re", "k_re"], ["ロ", "ro", "k_ro"] ],
    "w": [ ["ワ", "wa", "k_wa"], ["ヲ", "wo", "k_wo"], ["ン", "n", "k_n"] ],
    "g": [ ["ガ", "ga", "k_ga"], ["ギ", "gi", "k_gi"], ["グ", "gu", "k_gu"], ["ゲ", "ge", "k_ge"], ["ゴ", "go", "k_go"] ],
    "z": [ ["ザ", "za", "k_za"], ["ジ", "ji", "k_ji"], ["ズ", "zu", "k_zu"], ["ゼ", "ze", "k_ze"], ["ゾ", "zo", "k_zo"] ],
    "d": [ ["ダ", "da", "k_da"], ["ヂ", "dji", "k_dji"], ["ヅ", "dzu", "k_dzu"], ["デ", "de", "k_de"], ["ド", "do", "k_do"] ],
    "b": [ ["バ", "ba", "k_ba"], ["ビ", "bi", "k_bi"], ["ブ", "bu", "k_bu"], ["ベ", "be", "k_be"], ["ボ", "bo", "k_bo"] ],
    "p": [ ["パ", "pa", "k_pa"], ["ピ", "pi", "k_pi"], ["プ", "pu", "k_pu"], ["ペ", "pe", "k_pe"], ["ポ", "po", "k_po"] ],
    "ky": [ ["キャ", "kya", "k_kya"], ["キュ", "kyu", "k_kyu"], ["キョ", "kyo", "k_kyo"] ],
    "sy": [ ["シャ", "sha", "k_sha"], ["シュ", "shu", "k_shu"], ["ショ", "sho", "k_sho"] ],
    "ty": [ ["チャ", "cha", "k_cha"], ["チュ", "chu", "k_chu"], ["チョ", "cho", "k_cho"] ],
    "ny": [ ["ニャ", "nya", "k_nya"], ["ニュ", "nyu", "k_nyu"], ["ニョ", "nyo", "k_nyo"] ],
    "hy": [ ["ヒャ", "hya", "k_hya"], ["ヒュ", "hyu", "k_hyu"], ["ヒョ", "hyo", "k_hyo"] ],
    "my": [ ["ミャ", "mya", "k_mya"], ["ミュ", "myu", "k_myu"], ["ミョ", "myo", "k_myo"] ],
    "ry": [ ["リャ", "rya", "k_rya"], ["リュ", "ryu", "k_ryu"], ["リョ", "ryo", "k_ryo"] ],
    "gy": [ ["ギャ", "gya", "k_gya"], ["ギュ", "gyu", "k_gyu"], ["ギョ", "gyo", "k_gyo"] ],
    "jy": [ ["ジャ", "ja", "k_ja"], ["ジュ", "ju", "k_ju"], ["ジョ", "jo", "k_jo"] ],
    "by": [ ["ビャ", "bya", "k_bya"], ["ビュ", "byu", "k_byu"], ["ビョ", "byo", "k_byo"] ],
    "py": [ ["ピャ", "pya", "k_pya"], ["ピュ", "pyu", "k_pyu"], ["ピョ", "pyo", "k_pyo"] ],
    "special_f": [ ["ファ", "fa", "k_fa"], ["フィ", "fi", "k_fi"], ["フェ", "fe", "k_fe"], ["フォ", "fo", "k_fo"], ["フュ", "fyu", "k_fyu"] ],
    "special_w": [ ["ウィ", "wi", "k_wi"], ["ウェ", "we", "k_we"], ["ウォ", "uo", "k_uo"], ["ヴィ", "vi", "k_vi"], ["ヴェ", "ve", "k_ve"], ["ヴォ", "vo", "k_vo"] ],
    "special_v": [ ["ヴァ", "va", "k_va"], ["ヴィ", "vi", "k_vi"], ["ヴェ", "ve", "k_ve"], ["ヴォ", "vo", "k_vo"] ],
    "special_tsu": [ ["ツァ", "tsa", "k_tsa"], ["ツィ", "tsi", "k_tsi"], ["ツェ", "tse", "k_tse"], ["ツォ", "tso", "k_tso"] ],
    "special_e": [ ["チェ", "che", "k_che"], ["シェ", "she", "k_she"], ["ジェ", "je", "k_je"] ],
    "special_t": [ ["ティ", "ti", "k_ti"], ["ディ", "di", "k_di"], ["デュ", "du", "k_du"], ["トゥ", "tu", "k_tu"] ],
    "lookalike_1": [ ["シ", "shi", "k_shi","si"], ["ツ", "tsu", "k_tsu"], ["ソ", "so", "k_so"], ["ン", "n", "k_n"], ["ノ", "no", "k_no"] ],
    "lookalike_2": [ ["ウ", "u", "k_u"], ["フ", "fu", "k_fu"], ["ワ", "wa", "k_wa"], ["ラ", "ra", "k_ra"], ["ス", "su", "k_su"], ["ヌ", "nu", "k_nu"], ["ヲ", "wo", "k_wo"] ]
};

export const charsToGroups: CharsToGroups = {
    "ア": ["base"], "a": ["base"],
    "イ": ["base"], "i": ["base"],
    "ウ": ["base","lookalike_2"], "u": ["base","lookalike_2"],
    "エ": ["base"], "e": ["base"],
    "オ": ["base"], "o": ["base"],
    "カ": ["k"], "ka": ["k"],
    "キ": ["k"], "ki": ["k"],
    "ク": ["k"], "ku": ["k"],
    "ケ": ["k"], "ke": ["k"],
    "コ": ["k"], "ko": ["k"],
    "サ": ["s"], "sa": ["s"],
    "シ": ["s","lookalike_1"], "shi": ["s","lookalike_1"],
    "ス": ["s","lookalike_2"], "su": ["s","lookalike_2"],
    "セ": ["s"], "se": ["s"],
    "ソ": ["s","lookalike_1"], "so": ["s","lookalike_1"],
    "タ": ["t"], "ta": ["t"],
    "チ": ["t"], "chi": ["t"],
    "ツ": ["t","lookalike_1"], "tsu": ["t","lookalike_1"],
    "テ": ["t"], "te": ["t"],
    "ト": ["t"], "to": ["t"],
    "ナ": ["n"], "na": ["n"],
    "ニ": ["n"], "ni": ["n"],
    "ヌ": ["n","lookalike_2"], "nu": ["n","lookalike_2"],
    "ネ": ["n"], "ne": ["n"],
    "ノ": ["n","lookalike_1"], "no": ["n","lookalike_1"],
    "ハ": ["h"], "ha": ["h"],
    "ヒ": ["h"], "hi": ["h"],
    "フ": ["h","lookalike_2"], "fu": ["h","lookalike_2"],
    "ヘ": ["h"], "he": ["h"],
    "ホ": ["h"], "ho": ["h"],
    "マ": ["m"], "ma": ["m"],
    "ミ": ["m"], "mi": ["m"],
    "ム": ["m"], "mu": ["m"],
    "メ": ["m"], "me": ["m"],
    "モ": ["m"], "mo": ["m"],
    "ヤ": ["y"], "ya": ["y"],
    "ユ": ["y"], "yu": ["y"],
    "ヨ": ["y"], "yo": ["y"],
    "ラ": ["r","lookalike_2"], "ra": ["r","lookalike_2"],
    "リ": ["r"], "ri": ["r"],
    "ル": ["r"], "ru": ["r"],
    "レ": ["r"], "re": ["r"],
    "ロ": ["r"], "ro": ["r"],
    "ワ": ["w","lookalike_2"], "wa": ["w","lookalike_2"],
    "ヲ": ["w","lookalike_2"], "wo": ["w","lookalike_2"],
    "ン": ["w","lookalike_1"], "n": ["w","lookalike_1"],
    "ガ": ["g"], "ga": ["g"],
    "ギ": ["g"], "gi": ["g"],
    "グ": ["g"], "gu": ["g"],
    "ゲ": ["g"], "ge": ["g"],
    "ゴ": ["g"], "go": ["g"],
    "ザ": ["z"], "za": ["z"],
    "ジ": ["z"], "ji": ["z"],
    "ズ": ["z"], "zu": ["z"],
    "ゼ": ["z"], "ze": ["z"],
    "ゾ": ["z"], "zo": ["z"],
    "ダ": ["d"], "da": ["d"],
    "ヂ": ["d"], "dji": ["d"],
    "ヅ": ["d"], "dzu": ["d"],
    "デ": ["d"], "de": ["d"],
    "ド": ["d"], "do": ["d"],
    "バ": ["b"], "ba": ["b"],
    "ビ": ["b"], "bi": ["b"],
    "ブ": ["b"], "bu": ["b"],
    "ベ": ["b"], "be": ["b"],
    "ボ": ["b"], "bo": ["b"],
    "パ": ["p"], "pa": ["p"],
    "ピ": ["p"], "pi": ["p"],
    "プ": ["p"], "pu": ["p"],
    "ペ": ["p"], "pe": ["p"],
    "ポ": ["p"], "po": ["p"],
    "キャ": ["ky"], "kya": ["ky"],
    "キュ": ["ky"], "kyu": ["ky"],
    "キョ": ["ky"], "kyo": ["ky"],
    "シャ": ["sy"], "sha": ["sy"],
    "シュ": ["sy"], "shu": ["sy"],
    "ショ": ["sy"], "sho": ["sy"],
    "チャ": ["ty"], "cha": ["ty"],
    "チュ": ["ty"], "chu": ["ty"],
    "チョ": ["ty"], "cho": ["ty"],
    "ニャ": ["ny"], "nya": ["ny"],
    "ニュ": ["ny"], "nyu": ["ny"],
    "ニョ": ["ny"], "nyo": ["ny"],
    "ヒャ": ["hy"], "hya": ["hy"],
    "ヒュ": ["hy"], "hyu": ["hy"],
    "ヒョ": ["hy"], "hyo": ["hy"],
    "ミャ": ["my"], "mya": ["my"],
    "ミュ": ["my"], "myu": ["my"],
    "ミョ": ["my"], "myo": ["my"],
    "リャ": ["ry"], "rya": ["ry"],
    "リュ": ["ry"], "ryu": ["ry"],
    "リョ": ["ry"], "ryo": ["ry"],
    "ギャ": ["gy"], "gya": ["gy"],
    "ギュ": ["gy"], "gyu": ["gy"],
    "ギョ": ["gy"], "gyo": ["gy"],
    "ジャ": ["jy"], "ja": ["jy"],
    "ジュ": ["jy"], "ju": ["jy"],
    "ジョ": ["jy"], "jo": ["jy"],
    "ビャ": ["by"], "bya": ["by"],
    "ビュ": ["by"], "byu": ["by"],
    "ビョ": ["by"], "byo": ["by"],
    "ピャ": ["py"], "pya": ["py"],
    "ピュ": ["py"], "pyu": ["py"],
    "ピョ": ["py"], "pyo": ["py"],
    "ファ": ["special_f"], "fa": ["special_f"],
    "フィ": ["special_f"], "fi": ["special_f"],
    "フェ": ["special_f"], "fe": ["special_f"],
    "フォ": ["special_f"], "fo": ["special_f"],
    "フュ": ["special_f"], "fyu": ["special_f"],
    "ウィ": ["special_w"], "wi": ["special_w"],
    "ウェ": ["special_w"], "we": ["special_w"],
    "ウォ": ["special_w"], "uo": ["special_w"], // 'uo' should probably be 'wo'
    "ヴィ": ["special_w","special_v"], "vi": ["special_w","special_v"],
    "ヴェ": ["special_w","special_v"], "ve": ["special_w","special_v"],
    "ヴォ": ["special_w","special_v"], "vo": ["special_w","special_v"],
    "ヴァ": ["special_v"], "va": ["special_v"],
    "ツァ": ["special_tsu"], "tsa": ["special_tsu"],
    "ツィ": ["special_tsu"], "tsi": ["special_tsu"],
    "ツェ": ["special_tsu"], "tse": ["special_tsu"],
    "ツォ": ["special_tsu"], "tso": ["special_tsu"],
    "チェ": ["special_e"], "che": ["special_e"],
    "シェ": ["special_e"], "she": ["special_e"],
    "ジェ": ["special_e"], "je": ["special_e"],
    "ティ": ["special_t"], "ti": ["special_t"],
    "ディ": ["special_t"], "di": ["special_t"],
    "デュ": ["special_t"], "du": ["special_t"],
    "トゥ": ["special_t"], "tu": ["special_t"]
};