export const groupsToChars = {
    'base': [ ['ア', 'a', 'k_a'], ['イ', 'i', 'k_i'], ['ウ', 'u', 'k_u'], ['エ', 'e', 'k_e'], ['オ', 'o', 'k_o'] ],
    'k': [ ['カ', 'ka', 'k_ka'], ['キ', 'ki', 'k_ki'], ['ク', 'ku', 'k_ku'], ['ケ', 'ke', 'k_ke'], ['コ', 'ko', 'k_ko'] ],
    's': [ ['サ', 'sa', 'k_sa'], ['シ', 'shi', 'k_shi','si'], ['ス', 'su', 'k_su'], ['セ', 'se', 'k_se'], ['ソ', 'so', 'k_so'] ],
    't': [ ['タ', 'ta', 'k_ta'], ['チ', 'chi', 'k_chi','ti'], ['ツ', 'tsu', 'k_tsu','tu'], ['テ', 'te', 'k_te'], ['ト', 'to', 'k_to'] ],
    'n': [ ['ナ', 'na', 'k_na'], ['ニ', 'ni', 'k_ni'], ['ヌ', 'nu', 'k_nu'], ['ネ', 'ne', 'k_ne'], ['ノ', 'no', 'k_no'] ],
    'h': [ ['ハ', 'ha', 'k_ha'], ['ヒ', 'hi', 'k_hi'], ['フ', 'fu', 'k_fu','hu'], ['ヘ', 'he', 'k_he'], ['ホ', 'ho', 'k_ho'] ],
    'm': [ ['マ', 'ma', 'k_ma'], ['ミ', 'mi', 'k_mi'], ['ム', 'mu', 'k_mu'], ['メ', 'me', 'k_me'], ['モ', 'mo', 'k_mo'] ],
    'y': [ ['ヤ', 'ya', 'k_ya'], ['ユ', 'yu', 'k_yu'], ['ヨ', 'yo', 'k_yo'] ],
    'r': [ ['ラ', 'ra', 'k_ra'], ['リ', 'ri', 'k_ri'], ['ル', 'ru', 'k_ru'], ['レ', 're', 'k_re'], ['ロ', 'ro', 'k_ro'] ],
    'w': [ ['ワ', 'wa', 'k_wa'], ['ヲ', 'wo', 'k_wo','o'], ['ン', 'n', 'k_n'] ],
    'lookalike_1': [ ['シ', 'shi', 'k_shi','si'], ['ツ', 'tsu', 'k_tsu','tu'], ['ソ', 'so', 'k_so'], ['ン', 'n', 'k_n'], ['ノ', 'no', 'k_no'] ],
    'lookalike_2': [ ['ウ', 'u', 'k_u'], ['フ', 'fu', 'k_fu','hu'], ['ワ', 'wa', 'k_wa'], ['ラ', 'ra', 'k_ra'], ['ス', 'su', 'k_su'], ['ヌ', 'nu', 'k_nu'], ['ヲ', 'wo', 'k_wo','o'] ],
    'g': [ ['ガ', 'ga', 'k_ga'], ['ギ', 'gi', 'k_gi'], ['グ', 'gu', 'k_gu'], ['ゲ', 'ge', 'k_ge'], ['ゴ', 'go', 'k_go'] ],
    'z': [ ['ザ', 'za', 'k_za'], ['ジ', 'ji', 'k_ji','zi'], ['ズ', 'zu', 'k_zu','du'], ['ゼ', 'ze', 'k_ze'], ['ゾ', 'zo', 'k_zo'] ],
    'd': [ ['ダ', 'da', 'k_da'], ['ヂ', 'ji', 'k_ji','di','dzi'], ['ヅ', 'zu', 'k_zu','dzu'], ['デ', 'de', 'k_de'], ['ド', 'do', 'k_do'] ],
    'b': [ ['バ', 'ba', 'k_ba'], ['ビ', 'bi', 'k_bi'], ['ブ', 'bu', 'k_bu'], ['ベ', 'be', 'k_be'], ['ボ', 'bo', 'k_bo'] ],
    'p': [ ['パ', 'pa', 'k_pa'], ['ピ', 'pi', 'k_pi'], ['プ', 'pu', 'k_pu'], ['ペ', 'pe', 'k_pe'], ['ポ', 'po', 'k_po'] ],
    'ky': [ ['キャ', 'kya', 'k_kya'], ['キュ', 'kyu', 'k_kyu'], ['キョ', 'kyo', 'k_kyo'] ],
    'sy': [ ['シャ', 'sha', 'k_sha','sya'], ['シュ', 'shu', 'k_shu','syu'], ['ショ', 'sho', 'k_sho','syo'] ],
    'ty': [ ['チャ', 'cha', 'k_cha','cya','tya'], ['チュ', 'chu', 'k_chu','cyu'], ['チョ', 'cho', 'k_cho','cyo'] ],
    'ny': [ ['ニャ', 'nya', 'k_nya'], ['ニュ', 'nyu', 'k_nyu'], ['ニョ', 'nyo', 'k_nyo'] ],
    'hy': [ ['ヒャ', 'hya', 'k_hya'], ['ヒュ', 'hyu', 'k_hyu'], ['ヒョ', 'hyo', 'k_hyo'] ],
    'my': [ ['ミャ', 'mya', 'k_mya'], ['ミュ', 'myu', 'k_myu'], ['ミョ', 'myo', 'k_myo'] ],
    'ry': [ ['リャ', 'rya', 'k_rya'], ['リュ', 'ryu', 'k_ryu'], ['リョ', 'ryo', 'k_ryo'] ],
    'gy': [ ['ギャ', 'gya', 'k_gya'], ['ギュ', 'gyu', 'k_gyu'], ['ギョ', 'gyo', 'k_gyo'] ],
    'jy': [ ['ジャ', 'ja', 'k_ja','jya'], ['ジュ', 'ju', 'k_ju','jyu'], ['ジョ', 'jo', 'k_jo','jyo'] ],
    'by': [ ['ビャ', 'bya', 'k_bya'], ['ビュ', 'byu', 'k_byu'], ['ビョ', 'byo', 'k_byo'] ],
    'py': [ ['ピャ', 'pya', 'k_pya'], ['ピュ', 'pyu', 'k_pyu'], ['ピョ', 'pyo', 'k_pyo'] ],
    'special_f': [ ['ファ', 'fa', 'k_fa'], ['フィ', 'fi', 'k_fi'], ['フェ', 'fe', 'k_fe'], ['フォ', 'fo', 'k_fo'], ['フュ', 'fyu', 'k_fyu'] ],
    'special_w': [ ['ウィ', 'wi', 'k_wi'], ['ウェ', 'we', 'k_we'], ['ウォ', 'wo', 'k_wo'], ['ヴァ', 'va', 'k_va'], ['ヴィ', 'vi', 'k_vi'], ['ヴェ', 've', 'k_ve'], ['ヴォ', 'vo', 'k_vo'] ],
    'special_v': [ ['ヴァ', 'va', 'k_va'], ['ヴィ', 'vi', 'k_vi'], ['ヴェ', 've', 'k_ve'], ['ヴォ', 'vo', 'k_vo'] ],
    'special_tsu': [ ['ツァ', 'tsa', 'k_tsa'], ['ツィ', 'tsi', 'k_tsi'], ['ツェ', 'tse', 'k_tse'], ['ツォ', 'tso', 'k_tso'] ],
    'special_e': [ ['チェ', 'che', 'k_che'], ['シェ', 'she', 'k_she'], ['ジェ', 'je', 'k_je'] ],
    'special_t': [ ['ティ', 'ti', 'k_ti'], ['ディ', 'di', 'k_di'], ['デュ', 'du', 'k_du'], ['トゥ', 'tu', 'k_tu'] ]
};

export const charsToGroups = {
    
};