import { CharsToGroups, GroupsToChars } from "@/types";

export const groupsToChars: GroupsToChars = {
    "k_base": [ ["ア", "a", "k_a"], ["イ", "i", "k_i"], ["ウ", "u", "k_u"], ["エ", "e", "k_e"], ["オ", "o", "k_o"] ],
    "k_k": [ ["カ", "ka", "k_ka"], ["キ", "ki", "k_ki"], ["ク", "ku", "k_ku"], ["ケ", "ke", "k_ke"], ["コ", "ko", "k_ko"] ],
    "k_s": [ ["サ", "sa", "k_sa"], ["シ", "shi", "k_shi"], ["ス", "su", "k_su"], ["セ", "se", "k_se"], ["ソ", "so", "k_so"] ],
    "k_t": [ ["タ", "ta", "k_ta"], ["チ", "chi", "k_chi"], ["ツ", "tsu", "k_tsu"], ["テ", "te", "k_te"], ["ト", "to", "k_to"] ],
    "k_n": [ ["ナ", "na", "k_na"], ["ニ", "ni", "k_ni"], ["ヌ", "nu", "k_nu"], ["ネ", "ne", "k_ne"], ["ノ", "no", "k_no"] ],
    "k_h": [ ["ハ", "ha", "k_ha"], ["ヒ", "hi", "k_hi"], ["フ", "fu", "k_fu"], ["ヘ", "he", "k_he"], ["ホ", "ho", "k_ho"] ],
    "k_m": [ ["マ", "ma", "k_ma"], ["ミ", "mi", "k_mi"], ["ム", "mu", "k_mu"], ["メ", "me", "k_me"], ["モ", "mo", "k_mo"] ],
    "k_y": [ ["ヤ", "ya", "k_ya"], ["ユ", "yu", "k_yu"], ["ヨ", "yo", "k_yo"] ],
    "k_r": [ ["ラ", "ra", "k_ra"], ["リ", "ri", "k_ri"], ["ル", "ru", "k_ru"], ["レ", "re", "k_re"], ["ロ", "ro", "k_ro"] ],
    "k_w": [ ["ワ", "wa", "k_wa"], ["ヲ", "wo", "k_wo"], ["ン", "n", "k_n"] ],
    "k_g": [ ["ガ", "ga", "k_ga"], ["ギ", "gi", "k_gi"], ["グ", "gu", "k_gu"], ["ゲ", "ge", "k_ge"], ["ゴ", "go", "k_go"] ],
    "k_z": [ ["ザ", "za", "k_za"], ["ジ", "ji", "k_ji"], ["ズ", "zu", "k_zu"], ["ゼ", "ze", "k_ze"], ["ゾ", "zo", "k_zo"] ],
    "k_d": [ ["ダ", "da", "k_da"], ["ヂ", "dji", "k_dji"], ["ヅ", "dzu", "k_dzu"], ["デ", "de", "k_de"], ["ド", "do", "k_do"] ],
    "k_b": [ ["バ", "ba", "k_ba"], ["ビ", "bi", "k_bi"], ["ブ", "bu", "k_bu"], ["ベ", "be", "k_be"], ["ボ", "bo", "k_bo"] ],
    "k_p": [ ["パ", "pa", "k_pa"], ["ピ", "pi", "k_pi"], ["プ", "pu", "k_pu"], ["ペ", "pe", "k_pe"], ["ポ", "po", "k_po"] ],
    "k_ky": [ ["キャ", "kya", "k_kya"], ["キュ", "kyu", "k_kyu"], ["キョ", "kyo", "k_kyo"] ],
    "k_sy": [ ["シャ", "sha", "k_sha"], ["シュ", "shu", "k_shu"], ["ショ", "sho", "k_sho"] ],
    "k_ty": [ ["チャ", "cha", "k_cha"], ["チュ", "chu", "k_chu"], ["チョ", "cho", "k_cho"] ],
    "k_ny": [ ["ニャ", "nya", "k_nya"], ["ニュ", "nyu", "k_nyu"], ["ニョ", "nyo", "k_nyo"] ],
    "k_hy": [ ["ヒャ", "hya", "k_hya"], ["ヒュ", "hyu", "k_hyu"], ["ヒョ", "hyo", "k_hyo"] ],
    "k_my": [ ["ミャ", "mya", "k_mya"], ["ミュ", "myu", "k_myu"], ["ミョ", "myo", "k_myo"] ],
    "k_ry": [ ["リャ", "rya", "k_rya"], ["リュ", "ryu", "k_ryu"], ["リョ", "ryo", "k_ryo"] ],
    "k_gy": [ ["ギャ", "gya", "k_gya"], ["ギュ", "gyu", "k_gyu"], ["ギョ", "gyo", "k_gyo"] ],
    "k_jy": [ ["ジャ", "ja", "k_ja"], ["ジュ", "ju", "k_ju"], ["ジョ", "jo", "k_jo"] ],
    "k_by": [ ["ビャ", "bya", "k_bya"], ["ビュ", "byu", "k_byu"], ["ビョ", "byo", "k_byo"] ],
    "k_py": [ ["ピャ", "pya", "k_pya"], ["ピュ", "pyu", "k_pyu"], ["ピョ", "pyo", "k_pyo"] ],
    "k_special_f": [ ["ファ", "fa", "k_fa"], ["フィ", "fi", "k_fi"], ["フェ", "fe", "k_fe"], ["フォ", "fo", "k_fo"], ["フュ", "fyu", "k_fyu"] ],
    "k_special_w": [ ["ウィ", "wi", "k_wi"], ["ウェ", "we", "k_we"], ["ウォ", "wo", "k_uo"] ],
    "k_special_v": [ ["ヴァ", "va", "k_va"], ["ヴィ", "vi", "k_vi"], ["ヴェ", "ve", "k_ve"], ["ヴォ", "vo", "k_vo"] ],
    "k_special_tsu": [ ["ツァ", "tsa", "k_tsa"], ["ツィ", "tsi", "k_tsi"], ["ツェ", "tse", "k_tse"], ["ツォ", "tso", "k_tso"] ],
    "k_special_e": [ ["チェ", "che", "k_che"], ["シェ", "she", "k_she"], ["ジェ", "je", "k_je"] ],
    "k_special_t": [ ["ティ", "ti", "k_ti"], ["ディ", "di", "k_di"], ["デュ", "du", "k_du"], ["トゥ", "tu", "k_tu"] ]
};

export const charsToGroups: CharsToGroups = {
    "ア": ["k_base", "la_4"], "a": ["k_base", "la_4"],
    "イ": ["k_base"], "i": ["k_base"],
    "ウ": ["k_base", "la_2"], "u": ["k_base", "la_2"],
    "エ": ["k_base"], "e": ["k_base"],
    "オ": ["k_base"], "o": ["k_base"],
    "カ": ["k_k"], "ka": ["k_k"],
    "キ": ["k_k"], "ki": ["k_k"],
    "ク": ["k_k", "la_13"], "ku": ["k_k", "la_13"],
    "ケ": ["k_k", "la_13"], "ke": ["k_k", "la_13"],
    "コ": ["k_k", "la_12"], "ko": ["k_k", "la_12"],
    "サ": ["k_s", "la_7"], "sa": ["k_s", "la_7"],
    "シ": ["k_s", "la_1"], "shi": ["k_s", "la_1"],
    "ス": ["k_s", "la_2"], "su": ["k_s", "la_2"],
    "セ": ["k_s"], "se": ["k_s"],
    "ソ": ["k_s", "la_1"], "so": ["k_s", "la_1"],
    "タ": ["k_t", "la_13"], "ta": ["k_t", "la_13"],
    "チ": ["k_t", "la_11"], "chi": ["k_t", "la_11"],
    "ツ": ["k_t", "la_1"], "tsu": ["k_t", "la_1"],
    "テ": ["k_t", "la_11"], "te": ["k_t", "la_11"],
    "ト": ["k_t"], "to": ["k_t"],
    "ナ": ["k_n", "la_11"], "na": ["k_n", "la_11"],
    "ニ": ["k_n"], "ni": ["k_n"],
    "ヌ": ["k_n", "la_2"], "nu": ["k_n", "la_2"],
    "ネ": ["k_n"], "ne": ["k_n"],
    "ノ": ["k_n", "la_1"], "no": ["k_n", "la_1"],
    "ハ": ["k_h"], "ha": ["k_h"],
    "ヒ": ["k_h"], "hi": ["k_h"],
    "フ": ["k_h", "la_2"], "fu": ["k_h", "la_2"],
    "ヘ": ["k_h"], "he": ["k_h"],
    "ホ": ["k_h"], "ho": ["k_h"],
    "マ": ["k_m", "la_4"], "ma": ["k_m", "la_4"],
    "ミ": ["k_m"], "mi": ["k_m"],
    "ム": ["k_m"], "mu": ["k_m"],
    "メ": ["k_m", "la_11", "la_1"], "me": ["k_m", "la_11", "la_1"],
    "モ": ["k_m", "la_11"], "mo": ["k_m", "la_11"],
    "ヤ": ["k_y", "la_4"], "ya": ["k_y", "la_4"],
    "ユ": ["k_y", "la_12"], "yu": ["k_y", "la_12"],
    "ヨ": ["k_y"], "yo": ["k_y"],
    "ラ": ["k_r", "la_2"], "ra": ["k_r", "la_2"],
    "リ": ["k_r", "la_10"], "ri": ["k_r", "la_10"],
    "ル": ["k_r"], "ru": ["k_r"],
    "レ": ["k_r"], "re": ["k_r"],
    "ロ": ["k_r"], "ro": ["k_r"],
    "ワ": ["k_w", "la_2"], "wa": ["k_w", "la_2"],
    "ヲ": ["k_w", "la_2"], "wo": ["k_w", "la_2", "k_special_w"],
    "ン": ["k_w", "la_1"], "n": ["k_w", "la_1"],
    "ガ": ["k_g"], "ga": ["k_g"],
    "ギ": ["k_g"], "gi": ["k_g"],
    "グ": ["k_g"], "gu": ["k_g"],
    "ゲ": ["k_g"], "ge": ["k_g"],
    "ゴ": ["k_g"], "go": ["k_g"],
    "ザ": ["k_z"], "za": ["k_z"],
    "ジ": ["k_z"], "ji": ["k_z"],
    "ズ": ["k_z"], "zu": ["k_z"],
    "ゼ": ["k_z"], "ze": ["k_z"],
    "ゾ": ["k_z"], "zo": ["k_z"],
    "ダ": ["k_d"], "da": ["k_d"],
    "ヂ": ["k_d"], "dji": ["k_d"],
    "ヅ": ["k_d"], "dzu": ["k_d"],
    "デ": ["k_d"], "de": ["k_d"],
    "ド": ["k_d"], "do": ["k_d"],
    "バ": ["k_b"], "ba": ["k_b"],
    "ビ": ["k_b"], "bi": ["k_b"],
    "ブ": ["k_b"], "bu": ["k_b"],
    "ベ": ["k_b"], "be": ["k_b"],
    "ボ": ["k_b"], "bo": ["k_b"],
    "パ": ["k_p"], "pa": ["k_p"],
    "ピ": ["k_p"], "pi": ["k_p"],
    "プ": ["k_p"], "pu": ["k_p"],
    "ペ": ["k_p"], "pe": ["k_p"],
    "ポ": ["k_p"], "po": ["k_p"],
    "キャ": ["k_ky"], "kya": ["k_ky"],
    "キュ": ["k_ky"], "kyu": ["k_ky"],
    "キョ": ["k_ky"], "kyo": ["k_ky"],
    "シャ": ["k_sy"], "sha": ["k_sy"],
    "シュ": ["k_sy"], "shu": ["k_sy"],
    "ショ": ["k_sy"], "sho": ["k_sy"],
    "チャ": ["k_ty"], "cha": ["k_ty"],
    "チュ": ["k_ty"], "chu": ["k_ty"],
    "チョ": ["k_ty"], "cho": ["k_ty"],
    "ニャ": ["k_ny"], "nya": ["k_ny"],
    "ニュ": ["k_ny"], "nyu": ["k_ny"],
    "ニョ": ["k_ny"], "nyo": ["k_ny"],
    "ヒャ": ["k_hy"], "hya": ["k_hy"],
    "ヒュ": ["k_hy"], "hyu": ["k_hy"],
    "ヒョ": ["k_hy"], "hyo": ["k_hy"],
    "ミャ": ["k_my"], "mya": ["k_my"],
    "ミュ": ["k_my"], "myu": ["k_my"],
    "ミョ": ["k_my"], "myo": ["k_my"],
    "リャ": ["k_ry"], "rya": ["k_ry"],
    "リュ": ["k_ry"], "ryu": ["k_ry"],
    "リョ": ["k_ry"], "ryo": ["k_ry"],
    "ギャ": ["k_gy"], "gya": ["k_gy"],
    "ギュ": ["k_gy"], "gyu": ["k_gy"],
    "ギョ": ["k_gy"], "gyo": ["k_gy"],
    "ジャ": ["k_jy"], "ja": ["k_jy"],
    "ジュ": ["k_jy"], "ju": ["k_jy"],
    "ジョ": ["k_jy"], "jo": ["k_jy"],
    "ビャ": ["k_by"], "bya": ["k_by"],
    "ビュ": ["k_by"], "byu": ["k_by"],
    "ビョ": ["k_by"], "byo": ["k_by"],
    "ピャ": ["k_py"], "pya": ["k_py"],
    "ピュ": ["k_py"], "pyu": ["k_py"],
    "ピョ": ["k_py"], "pyo": ["k_py"],
    "ファ": ["k_special_f"], "fa": ["k_special_f"],
    "フィ": ["k_special_f"], "fi": ["k_special_f"],
    "フェ": ["k_special_f"], "fe": ["k_special_f"],
    "フォ": ["k_special_f"], "fo": ["k_special_f"],
    "フュ": ["k_special_f"], "fyu": ["k_special_f"],
    "ウィ": ["k_special_w"], "wi": ["k_special_w"],
    "ウェ": ["k_special_w"], "we": ["k_special_w"],
    "ウォ": ["k_special_w"],
    "ヴィ": ["k_special_v"], "vi": ["k_special_v"],
    "ヴェ": ["k_special_v"], "ve": ["k_special_v"],
    "ヴォ": ["k_special_v"], "vo": ["k_special_v"],
    "ヴァ": ["k_special_v"], "va": ["k_special_v"],
    "ツァ": ["k_special_tsu"], "tsa": ["k_special_tsu"],
    "ツィ": ["k_special_tsu"], "tsi": ["k_special_tsu"],
    "ツェ": ["k_special_tsu"], "tse": ["k_special_tsu"],
    "ツォ": ["k_special_tsu"], "tso": ["k_special_tsu"],
    "チェ": ["k_special_e"], "che": ["k_special_e"],
    "シェ": ["k_special_e"], "she": ["k_special_e"],
    "ジェ": ["k_special_e"], "je": ["k_special_e"],
    "ティ": ["k_special_t"], "ti": ["k_special_t"],
    "ディ": ["k_special_t"], "di": ["k_special_t"],
    "デュ": ["k_special_t"], "du": ["k_special_t"],
    "トゥ": ["k_special_t"], "tu": ["k_special_t"]
};